version: "3.9"
services:
  postgres:
    container_name: db-1
    build:
      context: .
      dockerfile: pg.dockerfile
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - custom

  pgadmin:
    container_name: pgadmin-1
    image: dpage/pgadmin${PGADMIN_VERSION}
    env_file:
      - .env
    volumes:
      - "pgadmin-data:${PGADMIN_DATA}"
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - custom

#  postgres_exporter:
#    container_name: exporter_container
#    image: prometheuscommunity/postgres-exporter:v0.15.0
#    environment:
#      DATA_SOURCE_URI: "postgres:5432/postgres?sslmode=disable"
#      DATA_SOURCE_USER: "postgres"
#      DATA_SOURCE_PASS: "postgres"
#      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
#    volumes:
#      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
#    ports:
#      - "9187:9187"
#    restart: unless-stopped
#    networks:
#      - custom

volumes:
  db-data:
  pgadmin-data:

networks:
  custom:
    driver: bridge