# Generated by Django 4.2.6 on 2023-12-03 18:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Отдел кратко",
                        max_length=50,
                        verbose_name="Отдел кратко",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название отдела",
                        max_length=255,
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "additional_info",
                    models.CharField(
                        blank=True,
                        help_text="Дополнительная информация по отделу",
                        max_length=255,
                        verbose_name="Доп информация",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Краткое название должности",
                        max_length=50,
                        verbose_name="Должность кратко",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Должность", max_length=255, verbose_name="Должность"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkingUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Рассылка", max_length=255, verbose_name="Название"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("+", "Включена"),
                            ("-", "Отключена"),
                            ("X", "Неактивна"),
                        ],
                        default="+",
                        max_length=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("D", "1 раз в день"),
                            ("DD", "Несколько раз в день"),
                            ("W", "1 раз в неделю"),
                            ("O", "Однократно"),
                        ],
                        default="D",
                        max_length=2,
                        verbose_name="Частота",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "system_name",
                    models.CharField(max_length=50, verbose_name="Название в системе"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("+", "Работает"),
                            ("-", "Уволен"),
                            ("X", "Удалить из рассылки"),
                        ],
                        default="+",
                        max_length=1,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("М", "Мужчина"),
                            ("Ж", "Женщина"),
                            ("-", "Не указано"),
                        ],
                        default="М",
                        max_length=1,
                        null=True,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emaillist.department",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "subscription",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите подписки",
                        to="emaillist.subscription",
                        verbose_name="Подписки",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="emaillist.title",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "department",
                    "status",
                    "title",
                    "last_name",
                    "first_name",
                ],
            },
        ),
    ]
