# Generated by Django 4.2.6 on 2023-12-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("emaillist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="subscription",
        ),
        migrations.CreateModel(
            name="Manager2Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "managers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emaillist.manager",
                    ),
                ),
                (
                    "subscriptions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emaillist.subscription",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="manager",
            name="subscriptions",
            field=models.ManyToManyField(
                through="emaillist.Manager2Subscription", to="emaillist.subscription"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="managers",
            field=models.ManyToManyField(
                through="emaillist.Manager2Subscription", to="emaillist.manager"
            ),
        ),
    ]
