# Generated by Django 4.2.6 on 2023-12-04 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("emaillist", "0002_remove_manager_subscription_manager2subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager2subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
